export const SET_PAGE_CONTENT = 'SET_PAGE_CONTENT';
export const SET_BURGER_DETAIL = 'SET_BURGER_DETAIL';
export const SET_PAGE_TOTAL = 'SET_PAGE_TOTAL';
export const SET_ITEM_NUM = 'SET_ITEM_NUM';
export const SET_ITEM_BUNS = 'SET_ITEM_BUNS';
export const SET_ITEM_MEAT = 'SET_ITEM_MEAT';
export const SET_ITEM_PRICE = 'SET_ITEM_PRICE';
export const ADD_INGREDIENT1 = 'ADD_INGREDIENT1';
export const REMOVE_INGREDIENT1 = 'REMOVE_INGREDIENT1';
export const ADD_INGREDIENT2 = 'ADD_INGREDIENT2';
export const REMOVE_INGREDIENT2 = 'REMOVE_INGREDIENT2';
export const ADD_INGREDIENT3 = 'ADD_INGREDIENT3';
export const REMOVE_INGREDIENT3 = 'REMOVE_INGREDIENT3';
export const ADD_INGREDIENT4 = 'ADD_INGREDIENT4';
export const REMOVE_INGREDIENT4 = 'REMOVE_INGREDIENT4';
export const CHANGE_BUNS = 'CHANGE_BUNS';
export const CHANGE_MEAT = 'CHANGE_MEAT';
export const SET_MEAT_TOTAL = 'SET_MEAT_TOTAL';
export const ADD_CART_BUN = 'ADD_CART_BUN';
export const ADD_CART_MEAT = 'ADD_CART_MEAT';
// REQUEST FIREBASE LOGIN
export const BEGIN_LOGIN_REQUEST = "BEGIN_LOGIN_REQUEST";
export const SUCCESS_LOGIN_REQUEST = "SUCCESS_LOGIN_REQUEST";
export const FAIL_LOGIN_REQUEST = "FAIL_LOGIN_REQUEST";
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";

// REQUEST FIREBASE REGISTER
export const BEGIN_REGISTER_REQUEST = "BEGIN_REGISTER_REQUEST";
export const SUCCESS_REGISTER_REQUEST = "SUCCESS_REGISTER_REQUEST";
export const FAIL_REGISTER_REQUEST = "FAIL_REGISTER_REQUEST";

export const LOGIN_STATE = 'LOGIN_STATE';
// export const BEGIN_COMMENT = 'BEGIN_COMMENT';
// export const SUCCESS_COMMENT = 'SUCCESS_COMMENT';

export const SET_ISONTOUCH = 'SET_ISONTOUCH';